[package]
name = "calory_counting"
version = "0.1.0"
authors = ["Laurent Cocault <laurent.cocault@capgemini.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
